### PR TITLE
Use python3 as default in bionic image

### PR DESCRIPTION
**Pull request by rosiereflo**

### CODE REVIEW

**Comment by gautierbureau** [comment]
For me there is no need for this change. I removed python2.7 install from the image to avoid any hidden use of it. The mechanism of DYNAWO_PYTHON_COMMAND should do the job without having any python command in the PATH.

**Comment by rosiereflo** [comment]
Let's see how it goes then, and we'll see afterwards if this one is needed

**Comment by gautierbureau** [comment]
With only Python3 on the image I get the following error while compiling a model
```
Traceback (most recent call last):
  File "/home/dynawo_travis/dynawo/install/gcc7/master/Release-cxx11/shared/dynawo/sbin/writeModel.py", line 16, in <module>
    from factory import Factory
  File "/home/dynawo_travis/dynawo/install/gcc7/master/Release-cxx11/shared/dynawo/sbin/factory.py", line 19
    from __builtin__ import False
                                ^
SyntaxError: invalid syntax
```

**Comment by gautierbureau** [comment]
From [this](https://stackoverflow.com/questions/55725873/what-is-the-purpose-of-from-builtin-import-true) I get that it is not valid in python3

**Comment by rosiereflo** [comment]
Let's see

**Pull request closed without merging**
